### ISSUE TITLE
Exception on File Download

### ISSUE THREAD

**Issue by guipedral** [Azure/azure-batch-samples#225]
I can't download a file from task node. I'am getting this exeception:

Microsoft.Azure.Batch.Common.BatchException: Operation returned an invalid status code 'Forbidden' ---> Microsoft.Azure.Batch.Protocol.Models.BatchErrorException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Azure.Batch.Protocol.FileOperations.<GetPropertiesFromTaskWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestWithCancellationAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestAsync>d__40.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.ProtocolLayer.<ProcessAndExecuteBatchRequest>d__84`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.ProtocolLayer.<GetNodeFilePropertiesByTask>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.JobOperations.<GetNodeFileAsyncImpl>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.BatchExplorer.Models.TaskModel.<DownloadTaskFile>d__58.MoveNext() in C:\Users\g.pedral.santos\Desktop\azure batch\azure-batch-samples-master\CSharp\BatchExplorer\Models\TaskModel.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.BatchExplorer.Models.TaskModel.<GetTaskFileAsync>d__56.MoveNext() in C:\Users\g.pedral.santos\Desktop\azure batch\azure-batch-samples-master\CSharp\BatchExplorer\Models\TaskModel.cs:line 356
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.BatchExplorer.ViewModels.MainViewModel.<DownloadFileAsync>d__215.MoveNext() in C:\Users\g.pedral.santos\Desktop\azure batch\azure-batch-samples-master\CSharp\BatchExplorer\ViewModels\MainViewModel.cs:line 1728
Request Information
ClientRequestId:
RequestId:6cbffd54-1fc7-48cd-a56f-4ec3a5ab9cae
HttpStatusCode:Forbidden
StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

![screenshot 209](https://user-images.githubusercontent.com/5133686/27808525-c0267726-601e-11e7-8660-fabaa6dc70f7.png)

**Comment by matthchr** [comment]
Hi @guipedral - I'm looking into this.

**Comment by guipedral** [comment]
If need, I can share my account name/key. Tks

**Comment by matthchr** [comment]
I can get your account name from the RequestId in the callstack you posted above, and you shouldn't ever share your account key with anybody you don't trust.

I think I have all the information I need to diagnose the problem... I'll let you know when we know what's going on.

**Comment by guipedral** [comment]
Thanks a lot!

**Comment by matthchr** [comment]
There is a service bug which is causing this behavior for requests which contain `%2F` or `%5D` (the URL encoded forms of `/` and `\`).

We are rolling out a fix to mitigate the issue. You should hopefully see things start working again soon.

**Comment by matthchr** [comment]
This was fixed a few days after my last comment but I forgot to respond. Closing this now as the issue is resolved.

**Comment by kjayantmenon** [comment]
This issue persists - we are running in to this one intermittently.

**Comment by bgklein** [comment]
@kjayantmenon BatchExplorer v1 is now deprecated. You should switch to using [BatchExplorer ](https://github.com/Azure/BatchExplorer) v2 (formerly BatchLabs), which is getting active funding.
